"""Reusable learning utilities for the transformers project."""

from .attention import extract_attention_matrix, visualize_attention
from .baseline import (
    BaselineEvaluation,
    FrozenEmbeddingDataset,
    FrozenEmbeddingSplit,
    evaluate_logistic_regression,
    prepare_frozen_embedding_dataset,
    save_baseline_results,
    split_frozen_embedding_dataset,
    train_logistic_regression,
)
from .datasets import (
    LABEL_COLUMN,
    SST2_LABEL_MAP,
    SST2_METADATA,
    TEXT_COLUMN,
    SentimentDatasetMetadata,
    SentimentDatasetValidationError,
    SST2DownloadError,
    adapt_sst2_split,
    ensure_sst2_train_data,
    get_class_counts,
    validate_sentiment_dataframe,
)
from .modeling import (
    ProgressCallback,
    extract_first_token_representation,
    get_embeddings,
    load_model,
    similarity,
)
from .tokenization import (
    DEFAULT_MODEL_NAME,
    TokenizationWalkthrough,
    TokenizerInfo,
    explain_tokenization,
    inspect_tokenizer,
    load_tokenizer,
    tokenize_single_text,
    tokenize_texts,
)

__all__ = [
    "DEFAULT_MODEL_NAME",
    "LABEL_COLUMN",
    "ProgressCallback",
    "SST2_LABEL_MAP",
    "SST2_METADATA",
    "TEXT_COLUMN",
    "BaselineEvaluation",
    "FrozenEmbeddingDataset",
    "FrozenEmbeddingSplit",
    "SST2DownloadError",
    "SentimentDatasetMetadata",
    "SentimentDatasetValidationError",
    "TokenizationWalkthrough",
    "TokenizerInfo",
    "adapt_sst2_split",
    "ensure_sst2_train_data",
    "evaluate_logistic_regression",
    "explain_tokenization",
    "extract_attention_matrix",
    "extract_first_token_representation",
    "get_class_counts",
    "get_embeddings",
    "inspect_tokenizer",
    "load_model",
    "load_tokenizer",
    "prepare_frozen_embedding_dataset",
    "save_baseline_results",
    "similarity",
    "split_frozen_embedding_dataset",
    "tokenize_single_text",
    "tokenize_texts",
    "train_logistic_regression",
    "validate_sentiment_dataframe",
    "visualize_attention",
]
